# Generated by Django 3.2.9 on 2021-11-18 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions_api', '0003_useraccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='email',
            new_name='username',
        ),
    ]
