# Generated by Django 3.2.9 on 2021-11-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_api', '0006_auto_20211118_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='question',
            field=models.ManyToManyField(to='questions_api.Question'),
        ),
    ]
